// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_jrl-Be1pzA1TraN2AI895Q_v8WdPcPk',
    appId: '1:126438785534:web:da0a8570b564a1159e80af',
    messagingSenderId: '126438785534',
    projectId: 'itemreunite-de3e2',
    authDomain: 'itemreunite-de3e2.firebaseapp.com',
    storageBucket: 'itemreunite-de3e2.appspot.com',
    measurementId: 'G-HPKNJJCMST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmwpm5AP8mIc8K1XaXnbp6j7d9m_aeSIE',
    appId: '1:126438785534:android:086279e6569b64929e80af',
    messagingSenderId: '126438785534',
    projectId: 'itemreunite-de3e2',
    storageBucket: 'itemreunite-de3e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2vZJhRzBSH6JVhU8Vx6gc8xlKDTgmagI',
    appId: '1:126438785534:ios:5b0638d08bd65a1f9e80af',
    messagingSenderId: '126438785534',
    projectId: 'itemreunite-de3e2',
    storageBucket: 'itemreunite-de3e2.appspot.com',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2vZJhRzBSH6JVhU8Vx6gc8xlKDTgmagI',
    appId: '1:126438785534:ios:5b0638d08bd65a1f9e80af',
    messagingSenderId: '126438785534',
    projectId: 'itemreunite-de3e2',
    storageBucket: 'itemreunite-de3e2.appspot.com',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_jrl-Be1pzA1TraN2AI895Q_v8WdPcPk',
    appId: '1:126438785534:web:170ce7b6270e5cc69e80af',
    messagingSenderId: '126438785534',
    projectId: 'itemreunite-de3e2',
    authDomain: 'itemreunite-de3e2.firebaseapp.com',
    storageBucket: 'itemreunite-de3e2.appspot.com',
    measurementId: 'G-YC2EX3H9ZJ',
  );
}
